### ISSUE TITLE
Out of Control Graphics Kea Port

### ISSUE THREAD

**Issue by jesawyers** [nitroman123/Ship-Simulator-Realistic#1]
Sailing Fletcher from Kea Port.  
Sitting still there is no issue.
Command Throttle to Dead Slow.
Ship does not accelerate.
Graphics go crazy. (See screenshots)
![2021-12-28 (2)](https://user-images.githubusercontent.com/13039522/147614729-2ec054c5-1bf9-4cfd-b5f1-7e8592cf815e.png)
![2021-12-28 (1)](https://user-images.githubusercontent.com/13039522/147614736-b41d0b05-2254-4370-a8e1-cc6cd55a4d1a.png)

**Comment by nitroman123** [comment]
i hade this issue sometimes its an easy fix.

**Comment by nitroman123** [comment]
I tweak some values hopefully this wont happen again
