### ISSUE TITLE
Mooring Panel is Displayed on Mini Map

### ISSUE THREAD

**Issue by jesawyers** [nitroman123/Ship-Simulator-Realistic#10]
With the Mooring Panel displayed.
Clicking to make the Mini Map full screen, the Mooring Panel is displayed on the map.
![image](https://user-images.githubusercontent.com/13039522/147710268-580fd225-ca84-420b-b9e1-3150d3d1bc2f.png)

**Comment by nitroman123** [comment]
Yeap i noticed it too , i fixed it !!!
