### ISSUE TITLE
Game crashes on loading world

### ISSUE THREAD

**Issue by Kazbahn** [nitroman123/Ship-Simulator-Realistic#100]
Title : Bug

The game crashes on loading the map, after selecting a ship and starting location.

1. Choose any ship
2. Choose any spawn location in Greece
3. Load world
4. Game loads to 90% before crashing to desktop

Desktop
 - OS: Windows 10 Pro 64-bit
 - Game Version: V0.9.0.2
-  PC Specs:
Processor:	AMD Ryzen 7 3800X 8-Core Processor                3.90 GHz
Installed RAM:	16.0 GB
Graphics:         AMD Radeon RX 570 8GB

**Comment by nitroman123** [comment]
i will need a crash report if there is any

**Comment by Kazbahn** [comment]
Here is the crash report from windows event viewer, if that is any help.

Log Name:      Application
Source:        Application Error
Date:          10/02/2023 21:08:32
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-TGNCJLK
Description:
Faulting application name: ShipSimulatorRealistic.exe, version: 2021.3.16.5719, time stamp: 0x639793b5
Faulting module name: UnityPlayer.dll, version: 2021.3.16.5719, time stamp: 0x63979503
Exception code: 0xc0000005
Fault offset: 0x00000000012e5d8e
Faulting process ID: 0x20e8
Faulting application start time: 0x01d93d93acd5df82
Faulting application path: C:\Program Files (x86)\Steam\steamapps\common\Ship Simulator Realistic\ShipSimulatorRealistic.exe
Faulting module path: C:\Program Files (x86)\Steam\steamapps\common\Ship Simulator Realistic\UnityPlayer.dll
Report ID: d2dc79fb-53c7-4215-84ad-3a2642432805
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-02-10T21:08:32.1516074Z" />
    <EventRecordID>4912</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-TGNCJLK</Computer>
    <Security />
  </System>
  <EventData>
    <Data>ShipSimulatorRealistic.exe</Data>
    <Data>2021.3.16.5719</Data>
    <Data>639793b5</Data>
    <Data>UnityPlayer.dll</Data>
    <Data>2021.3.16.5719</Data>
    <Data>63979503</Data>
    <Data>c0000005</Data>
    <Data>00000000012e5d8e</Data>
    <Data>20e8</Data>
    <Data>01d93d93acd5df82</Data>
    <Data>C:\Program Files (x86)\Steam\steamapps\common\Ship Simulator Realistic\ShipSimulatorRealistic.exe</Data>
    <Data>C:\Program Files (x86)\Steam\steamapps\common\Ship Simulator Realistic\UnityPlayer.dll</Data>
    <Data>d2dc79fb-53c7-4215-84ad-3a2642432805</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by nitroman123** [comment]
Matter solved via discord
