### ISSUE TITLE
Mykonos capsizes

### ISSUE THREAD

**Issue by michael-taal** [nitroman123/Ship-Simulator-Realistic#22]
The Mykonos capsizes when you give to much rudder

**Comment by nitroman123** [comment]
yeah , if you give for example at 26 knts full rudder it will , i will reduce that

**Comment by michael-taal** [comment]
It mostly happens at full speed and with 10 degrees rudder and upward

**Comment by nitroman123** [comment]
> It mostly happens at full speed and with 10 degrees rudder and upward

ok i adjusted the COG of the ship , now its harder to capsize
