### ISSUE TITLE
Throttle Response

### ISSUE THREAD

**Issue by jesawyers** [nitroman123/Ship-Simulator-Realistic#3]
This will be a big issue with people trying to control their selected ship.
When a throttle demand is ordered it should not take but a few seconds to reach the ordered speed.

**Comment by jesawyers** [comment]
I would recommend a PID for throttle response.

**Comment by nitroman123** [comment]
I tweaked some values , in the next version you will let me know if things are changed , The fletcher will be the experiment ship

**Comment by jesawyers** [comment]
I was thinking, for the very large ships they do take some time to get up to speed.

**Comment by nitroman123** [comment]
this already exits but i didnt play too much with the values , i tweaked the values for next test version for the fletcher to tell me if you found any differences to acceleration
