### ISSUE TITLE
1. Ship speed increasing and decreasing too fast / 2. stern movement during maneuver too weak (if ship is not equipped with stern thruster)

### ISSUE THREAD

**Issue by DRGD24** [nitroman123/Ship-Simulator-Realistic#34]
1. When setting from full throttle ahead to zero or full astern, the ship stops really quickly. In reality, this would take a couple of minutes at least, considering a top speed around 25 kts and the size of a ferry. I experienced the same when from zero I set full speed ahead or astern, the ship gains speed too quickly. I would reccomend to modify acceleration and deceleration times, for a better and real behaviour of the vessel during harbour maneuver. Apart of that, I felt that the ships are well maneuvrable in open sea, at speed, and really well designed. 

2. If a ship is not equipped with stern thruster, the fastest way to move the stern to one side should be set one throttle full ahead and the other one full astern, using rudders at the same time. If I try that, the stern begins to move to one side, but really slowly. This type of ferry, using only the two stern propulsion motors, should have a great maneuvrability of their stern
![1](https://user-images.githubusercontent.com/102175120/159536630-b198505d-dfdf-4f79-87d3-a3ea19f627da.png)
.

**Comment by nitroman123** [comment]
this is happening to the main game or the playtest ?
