### ISSUE TITLE
Seas are Crazy when Selecting a New Wind Intensity

### ISSUE THREAD

**Issue by jesawyers** [nitroman123/Ship-Simulator-Realistic#36]
If you select a different Wind Intensity before starting the game, when you start the game the seas are crazy.  

I selected Light Breeze and when I start the game I get the follow seas...

![image](https://user-images.githubusercontent.com/13039522/161132574-d916349d-aec6-464c-87dd-2d02d141bc01.png)

**Comment by nitroman123** [comment]
also try to update , if you are still on 0.7.4.3 we are on 8.1.0

**Comment by jesawyers** [comment]
Updating to 8.1.0 fixed the issue.
