### ISSUE TITLE
Full Screen Map Controls

### ISSUE THREAD

**Issue by jesawyers** [nitroman123/Ship-Simulator-Realistic#39]
The red X in the full screen map to open/close mini map should not be visible or greyed out.

![image](https://user-images.githubusercontent.com/13039522/163598459-d5d22947-7846-41d7-851c-1a21947ff0ca.png)

**Comment by nitroman123** [comment]
its like this by design

**Comment by jesawyers** [comment]
No problem...please close this issue.
