### ISSUE TITLE
Separate Zoom Settings for Mini Map and Fullscreen Map ??

### ISSUE THREAD

**Issue by jesawyers** [nitroman123/Ship-Simulator-Realistic#41]
Is it possible to have separate zoom settings for mini map and fullscreen map?  I like having the fullscreen map zoomed out to look like a nautical chart.  I like having the mini map zoomed in to function like a radar.

Also, can you change the focus ship behavior to just center the ship without changing the zoom level?

**Comment by nitroman123** [comment]
for the next update i planed too keep the zoom
