### ISSUE TITLE
Ocean Color Picker

### ISSUE THREAD

**Issue by jesawyers** [nitroman123/Ship-Simulator-Realistic#46]
Wanted to change the color of the ocean.  The Color Picker is not showing any colors.

![image](https://user-images.githubusercontent.com/13039522/165842350-d9dcd0f8-b40e-4f25-8c4e-dffdb7301b9b.png)

**Comment by nitroman123** [comment]
to me is visible on build

**Comment by jesawyers** [comment]
Just checked in the test release and it is working.  This issue can be closed.
