### ISSUE TITLE
Initial Screen Alignment Issues

### ISSUE THREAD

**Issue by jesawyers** [nitroman123/Ship-Simulator-Realistic#47]
On my screen things are not lined up.

![image](https://user-images.githubusercontent.com/13039522/174447082-00612590-b842-4e09-89b8-670e5d77fc18.png)

**Comment by jesawyers** [comment]
I started a sailing hit the ESC back to Main Menu and get this...

![image](https://user-images.githubusercontent.com/13039522/174447158-3a71c7b9-1fc2-469a-b88f-69720b3f29f4.png)

**Comment by nitroman123** [comment]
thats weird , will investigate

**Comment by nitroman123** [comment]
i think i fixed them let me know if its ok so we can close this one

**Comment by jesawyers** [comment]
This is fixed and this issue can be closed.
