### ISSUE TITLE
Day Length Slider Value Incorrect

### ISSUE THREAD

**Issue by jesawyers** [nitroman123/Ship-Simulator-Realistic#5]
When you open weather panel, the Day Length value is 12 hours.

![image](https://user-images.githubusercontent.com/13039522/147691609-88a42e78-b02a-4c95-9c6b-04fde7cdf75f.png)

Move slider just a little you get the correct value.

![image](https://user-images.githubusercontent.com/13039522/147691691-785cbdfa-b280-4bb6-ba7b-37e7f9004c5c.png)

**Comment by nitroman123** [comment]
Basically there is not right value but you are correct the slider haven't the right value Will fix that

**Comment by nitroman123** [comment]
Fixed and set default time to 2 hours for a full length time
