### ISSUE TITLE
Path maker has issue!! and Hydraulics pop up on Dev Build 0.8.3.3

### ISSUE THREAD

**Issue by Dawnmist050** [nitroman123/Ship-Simulator-Realistic#52]
Hello! sometime the Path maker has a bug where there is another path checked on top of another so when you cross it you get that lil ine stuck there on the map! 

on sometime there is that hydraulics sign that stay stuck on the screen when it request you to turn it on !

**Comment by nitroman123** [comment]
Maybe we need to make a min distance check for points so can place them far enough , will investigate about that hydraulic sign

**Comment by nitroman123** [comment]
ok so today we are gonna test the path and i added a close button to the hydraulics helper

**Comment by Dawnmist050** [comment]
okie :)

**Comment by nitroman123** [comment]
@Dawnmist050  its the issue resolved so i can close this one ?
