### ISSUE TITLE
CG-67 Quick View Key 2

### ISSUE THREAD

**Issue by jesawyers** [nitroman123/Ship-Simulator-Realistic#54]
Can you move this quick view a little forward and a little down to get rid of the grey portion (top of the bridge) shown in the screen shot?

![image](https://user-images.githubusercontent.com/13039522/174658915-8bfff3ba-f61e-4d8e-b489-9ac743440e5c.png)

**Comment by nitroman123** [comment]
now its adjusted , tomorrow i will fix some things too and you will tell me to close this one

**Comment by jesawyers** [comment]
This is tested and complete.  It can be closed.
