### ISSUE TITLE
Before Spawning Start Point Selection

### ISSUE THREAD

**Issue by jesawyers** [nitroman123/Ship-Simulator-Realistic#58]
You select a region then a start point before spawning. If you click to change something on Sky and Weather the start point is unselected.  Then you have to go select the start point again.  Can the start point be remembered?

**Comment by nitroman123** [comment]
if the start button its interactable yes . it remembers the last position you click no matter how back you go

**Comment by jesawyers** [comment]
Ok Cool.  Can the port selected dot say red?  It makes me think that my start point was de-selected.

**Comment by nitroman123** [comment]
i will make that to today its kinda simple

**Comment by jesawyers** [comment]
In today's test release, this problem still exists.

**Comment by nitroman123** [comment]
i didnt implemented it , now its in and its working like a charm !!!
