### ISSUE TITLE
Fletcher - No Port/Stbd Running Lights Visible

### ISSUE THREAD

**Issue by jesawyers** [nitroman123/Ship-Simulator-Realistic#6]
On the Lights Panel Underway is selected.

**Comment by nitroman123** [comment]
The lights now , i really didnt add those lights cause i didnt know where they should be placed. See the pic and let know where should i put them

![Screenshot 2021-12-30 122513](https://user-images.githubusercontent.com/62849221/147743446-962edefe-fe6c-4159-9e19-ee6d5fc4c19b.png)

**Comment by nitroman123** [comment]
Closing this for now
