### ISSUE TITLE
Throttle - Dividing Line Missing

### ISSUE THREAD

**Issue by jesawyers** [nitroman123/Ship-Simulator-Realistic#60]
The dividing line between SLOW and HALF is missing.

**Comment by nitroman123** [comment]
can you send me a screen ?

**Comment by jesawyers** [comment]
There should be a black line where I have marked with the yellow lines.

![image](https://user-images.githubusercontent.com/13039522/175346983-669289ff-667b-48ee-8483-0aac67d3db81.png)

**Comment by nitroman123** [comment]
i can see that in the game maybe its sometimes , i will check

**Comment by nitroman123** [comment]
i fix , it was a problem in the panel , i found a setting that allows it to be crisp for 1080p monitors let me know for the next update it its fixed

**Comment by jesawyers** [comment]
Yep it's fixed and the issue can be closed.
