### ISSUE TITLE
Fletcher - No Anchor Panel

### ISSUE THREAD

**Issue by jesawyers** [nitroman123/Ship-Simulator-Realistic#62]
Testing anchoring and there is not icon at the top to open the Anchor Panel.

**Comment by nitroman123** [comment]
yes the ship has a design fault and i cant change it remove the anchors that are stuck with the model

**Comment by jesawyers** [comment]
That's right I guess I forgot.

Gregory, you pay a lot of money for these models.  These creators should update their models as problems are found and do it for free!!  I think you should approach the creator of the Fletcher model and asked for changes.  Remember the Fletcher masthead lights are not correct.

I would be willing to work with the developers to improve their models!!

**Comment by jesawyers** [comment]
If you can show me where you bought the Fletcher model, I can contact the 3D developer for you.

**Comment by jesawyers** [comment]
Problem Fixed.  This issue can be closed.
