### ISSUE TITLE
Throttle LED Function

### ISSUE THREAD

**Issue by jesawyers** [nitroman123/Ship-Simulator-Realistic#63]
In the below, note that the throttle is at Nav Full.

You can see the arrow indicator (circled in purple)  but notice that only the Nav Full LED is illuminated.

I believe one of these indicators, such as the arrow, works correctly as currently programmed.  However, I believe the LED's show ordered and only one LED is illuminated.

![image](https://user-images.githubusercontent.com/13039522/175099727-22819bf6-c71b-4e0a-bb9f-320a0f662644.png)

**Comment by Dawnmist050** [comment]
that LED you see is the requested speed from the helm and so when you see the LED  change is like the helm request the engineer to change the ship's speed

**Comment by jesawyers** [comment]
Talking with Dawnmist050, the LED's show requested.

**Comment by nitroman123** [comment]
i think ive made long ago when i didnt have this panel to support but now i will make it again !!!

**Comment by nitroman123** [comment]
just what i thought I had it made like a year before , i will add it today and upload an update with all the changes

**Comment by jesawyers** [comment]
I would go with a brighter shade of green. Like the one in the photo above.

**Comment by nitroman123** [comment]
i added to the current update a more green shade

**Comment by jesawyers** [comment]
This is fixed.  Issue can be closed.
