### ISSUE TITLE
Fletcher - Quick View 2

### ISSUE THREAD

**Issue by jesawyers** [nitroman123/Ship-Simulator-Realistic#64]
Can you move the Quick View 2 to be in front of the bridge windows?  So move forward and down.  

For all ships, the standard Quick View 2 should be in front of and level with the bridge windows.

**Comment by nitroman123** [comment]
just moved it !!! I will update today so let me know if its ok for you

**Comment by jesawyers** [comment]
view looks great.  you can close this issue.
