### ISSUE TITLE
Akizuki Sailing Out of Sifnos Problem

### ISSUE THREAD

**Issue by jesawyers** [nitroman123/Ship-Simulator-Realistic#67]
While leaving the Port of Sifnos on Akizuki, it appears I hit something and the ship began a violent sinking which locked up SSR.  I was in the center of the channel when exiting the port.  I was able to duplicate.

![image](https://user-images.githubusercontent.com/13039522/175613128-b0a14992-87e2-47d1-b098-1913ea70b2b1.png)

![image](https://user-images.githubusercontent.com/13039522/175614203-b682823b-2471-4e0e-976c-7a65cea96e37.png)

**Comment by jesawyers** [comment]
Here is the log file...

Found 4 interfaces on host : 0) 192.168.59.12 1) 192.168.225.1 2) 192.168.150.1 3) 192.168.56.1
Multi-casting "[IP] 192.168.59.12 [Port] 55000 [Flags] 2 [Guid] 3950112918 [EditorId] 3283699892 [Version] 1048832 [Id] WindowsPlayer(2,DESKTOP-6PH6MN0) [Debug] 0 [PackageName] WindowsPlayer [ProjectName] ShipSimulatorRealistic" to [225.0.0.222:54997]...
Initialize engine version: 2021.3.3f1 (af2e63e8f9bd)
[Subsystems] Discovering subsystems at path C:/Program Files (x86)/Steam/steamapps/common/Ship Simulator Realistic/ShipSimulatorRealistic_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1; jobified=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce RTX 2060 SUPER (ID=0x1f06)
    Vendor:   NVIDIA
    VRAM:     8031 MB
    Driver:   30.0.15.1295
<RI> Initializing input.

New input system (experimental) initialized
XInput1_3.dll not found. Trying XInput9_1_0.dll instead...
<RI> Input initialized.

<RI> Initialized touch support.

Couldn't create a Convex Mesh from source mesh "Ship_HulL_geo" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
Couldn't create a Convex Mesh from source mesh "ship_main" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
Couldn't create a Convex Mesh from source mesh "hull" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
Shader 'Enviro/Standard/SkyboxSimple': fallback shader 'None' not found
Shader 'Enviro/Clouds Particles Advanced': fallback shader 'Legacy Shader/Particles/Alpha Blended' not found
UnloadTime: 0.804900 ms
Intenet Ok
Couldn't create a Convex Mesh from source mesh "Plane" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 3.653100 ms
Right neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Top right neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Left neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Top left neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Bottom left neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Left neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Top neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Bottom neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Left neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Right neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Top right neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Bottom neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Bottom right neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Right neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Left neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Top left neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Top neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Bottom neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Bottom right neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Right neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Bottom neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Bottom right neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Right neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Top neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Left neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Top left neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Bottom right neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Right neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Left neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Top left neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Bottom left neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Left neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Left neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Top left neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Bottom right neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Right neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Bottom left neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Bottom neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Bottom right neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Right neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Bottom left neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Left neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Right neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Top right neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Right neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Top left neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Top neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Top neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Top right neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Bottom neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Left neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Top left neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Top neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Bottom right neighbor of the terrain has a different heightmap resolution. Stop neighboring.
Unloading 461 unused Assets / (33.9 MB). Loaded Objects now: 39901.
Memory consumption went from 4.96 GB to 4.92 GB.
Total: 33.825000 ms (FindLiveObjects: 2.025700 ms CreateObjectMapping: 2.234800 ms MarkObjects: 27.186000 ms  DeleteObjects: 2.378100 ms)

0.09327437
Screen position out of view frustum (screen pos 0.000000, 0.000000, 20000.000000) (Camera rect 0 0 1024 1024)
Crest.OceanPlanarReflection:OnPreRender()

[C:\buildslave\unity\build\Runtime\Camera\Camera.cpp line 1090235768]

Screen position out of view frustum (screen pos 1024.000000, 0.000000, 20000.000000) (Camera rect 0 0 1024 1024)
Crest.OceanPlanarReflection:OnPreRender()

[C:\buildslave\unity\build\Runtime\Camera\Camera.cpp line 1090235768]

Screen position out of view frustum (screen pos 0.000000, 0.000000, 20000.000000) (Camera rect 0 0 1024 1024)
Crest.OceanPlanarReflection:OnPreRender()

[C:\buildslave\unity\build\Runtime\Camera\Camera.cpp line 1090170280]

Screen position out of view frustum (screen pos 1024.000000, 0.000000, 20000.000000) (Camera rect 0 0 1024 1024)
Crest.OceanPlanarReflection:OnPreRender()

[C:\buildslave\unity\build\Runtime\Camera\Camera.cpp line 1090170280]

Saving to C:/Users/FlightSim/AppData/LocalLow/Gregory Nikolaidis/ShipSimulatorRealistic\save.sav
Unloading 4 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 28.391900 ms
Unloading 580 unused Assets / (1.98 GB). Loaded Objects now: 34110.
Memory consumption went from 4.72 GB to 2.74 GB.
Total: 129.730500 ms (FindLiveObjects: 1.546000 ms CreateObjectMapping: 1.590200 ms MarkObjects: 21.889600 ms  DeleteObjects: 104.704300 ms)

Intenet Ok

**Comment by nitroman123** [comment]
ok i found the reason that was happening , this was a chance of 1/10000000 to happen , after some travel the center of the world is moved in order we dont have any problems with physics and precision errors. So the moment that the ship entered the exit collider the whole scene moved and caused this problem. it wont happen again hopefully
