### ISSUE TITLE
Fletcher - Only 1 Masthead White Light

### ISSUE THREAD

**Issue by jesawyers** [nitroman123/Ship-Simulator-Realistic#7]
This will be true for most ships. and visible 360 degrees.

**Comment by jesawyers** [comment]
I checked a photo of Fletcher.  There is a small mast just behind the top radar antenna.  It appears to be about 2-3 meters above the radar antenna.

**Comment by nitroman123** [comment]
Send me the pick i will correctly add them to position

**Comment by jesawyers** [comment]
![image](https://user-images.githubusercontent.com/13039522/147772283-50e70113-b9d5-416e-8da4-e1ece56eee44.png)

**Comment by jesawyers** [comment]
**_I would not change anything about the masthead light._**
