### ISSUE TITLE
Change Default Day Length

### ISSUE THREAD

**Issue by jesawyers** [nitroman123/Ship-Simulator-Realistic#70]
Default day length is 1 hour.  Can we change to something longer like 10 hours?

**Comment by nitroman123** [comment]
you can change it from the weather panel , you can set any length you want

**Comment by jesawyers** [comment]
Yes indeed.  I talking about setting the default value when the game loads.  Every time the game loads, I have to change the day length to something else to make it more realistic.

**Comment by nitroman123** [comment]
ok made it 5 hours
