### ISSUE TITLE
Hit Something Sailing Out of Port of Serifos

### ISSUE THREAD

**Issue by jesawyers** [nitroman123/Ship-Simulator-Realistic#72]
Same issue as with the Port of Sifnos.

**Comment by nitroman123** [comment]
Yes I fixed it you don't have to report it again , hopefully I fixed it

**Comment by jesawyers** [comment]
Issue is still there.  I hit something but did not sink.

**Comment by jesawyers** [comment]
A few minutes later, I hit something and the ship spiraled up into the sky before finally sinking.  Also, with the ship upside down in the water the ship was doing 16 kts.

**Comment by jesawyers** [comment]
This is fixed.  Issue can be closed.
