### ISSUE TITLE
Mini-Map Alignment Around Serifos

### ISSUE THREAD

**Issue by jesawyers** [nitroman123/Ship-Simulator-Realistic#73]
IF you take a look at the attached screen shot, in the mini map that island is on my port quarter.  I zoomed in to make sure.   However in the ship view it is off the port bow.

There appears to be an alignment issue here.  This might be what is causing the issue of running into things when leaving the Port Serifos.

![image](https://user-images.githubusercontent.com/13039522/176012514-774496f6-d060-40e9-bce5-17a37c0d8bbf.png)

**Comment by nitroman123** [comment]
maybe , i will upload the update and tell me again

**Comment by jesawyers** [comment]
This is fixed.  Issue can be closed
