### ISSUE TITLE
Throttle Dead Slow Green LED

### ISSUE THREAD

**Issue by jesawyers** [nitroman123/Ship-Simulator-Realistic#79]
The dead slow green LED does not turn on when throttle has commanded dead slow.  I was in standby mode so the effect is greatly noticed.  Testing in run up mode I get the following.

![image](https://user-images.githubusercontent.com/13039522/177377704-adeea7b2-9539-4d2c-9361-b388815fc074.png)

**Comment by nitroman123** [comment]
ok i fixed it i never for some reason i had the 0.2 to 0.3 while the other ones 0.3 to 0.5 !!!
