### ISSUE TITLE
Fletcher - No Hydraulics Panel

### ISSUE THREAD

**Issue by jesawyers** [nitroman123/Ship-Simulator-Realistic#81]
There is no hydraulics panel under the ship info page.  This prevents testing reeling in the anchor.

**Comment by nitroman123** [comment]
maybe i forgot , did flecher had hydralics and similar sounds with the modern ships ? 

thats why i didnt have add hydraulics

**Comment by jesawyers** [comment]
Fletcher did not have hydraulics because the 3D model did not support dropping of the anchors.  Now that we can drop the anchors, we need hydraulics to be able to reel in the anchors like the other ships.

I did try to reel in the anchors but it did not work.

**Comment by jesawyers** [comment]
Latest test release (07/12/2022), no hydraulics panel.

**Comment by nitroman123** [comment]
You don't need it for the anchors , don't know but it doesn't fit me to add
hydraulic panel for Fletcher

**Comment by jesawyers** [comment]
Ok...I will test again and let you know.

**Comment by jesawyers** [comment]
Problem fixed.  This issue can be closed.
