### ISSUE TITLE
Fletcher - Port/Stbd Running Lights Reversed

### ISSUE THREAD

**Issue by jesawyers** [nitroman123/Ship-Simulator-Realistic#83]
The port and starboard running light colors are reversed.

**Comment by nitroman123** [comment]
what do you mean ? 
 

the green and red ? Green is right and Red left right ?

**Comment by jesawyers** [comment]
Yes...the green and red.  Red is Port and Green is Starboard.

**Comment by jesawyers** [comment]
Issue fixed and can be closed.
