### ISSUE TITLE
Fletcher - Propellers Not Rotating Correctly

### ISSUE THREAD

**Issue by jesawyers** [nitroman123/Ship-Simulator-Realistic#85]
The propellers are not rotating around the center axis of the propeller.  They are offset.  Here is a link to a video showing the issue...

https://1drv.ms/v/s!AlKjpQ64JuFVhOpvvhTx77Ioh_i7CQ?e=52mdNk

**Comment by nitroman123** [comment]
i saw it ive made a mistake while i reposition them

**Comment by jesawyers** [comment]
The rotation is better but there is still a small oscillation.

**Comment by jesawyers** [comment]
The oscillation is very small.  This issue can be closed.
