### ISSUE TITLE
Can't Attach Mooring Lines

### ISSUE THREAD

**Issue by jesawyers** [nitroman123/Ship-Simulator-Realistic#9]
Trying to dock the Fletcher in Tinos.  
In the screen shot you can see that I am very close.
I Left Click a ship mooring point, then Left Click a shore mooring point.  Nothing.
I've tried other ship/shore combinations.  Nothing.
I've closed the Mooring Panel and reopened.  Nothing.
It keeps telling me to select a ship point when I click on a shore point after selecting the ship point first.
That message should be one line.

**I would recommend when you select a ship based mooring point, change it's color to indicated that it was selected.** 

![image](https://user-images.githubusercontent.com/13039522/147709924-6b35a23b-42c3-470d-af74-8d15b54eca0f.png)

**Comment by nitroman123** [comment]
fixed it , was kinda hard cause the collider of the ship, made some adjustments to the code. now working currently
